### ISSUE TITLE
https for parks.api.codefornrv.org

### ISSUE THREAD

**Issue by jhawley** [CodeforNRV/NRV-Park-Finder#5]
Chrome desktop is rejecting api requests with the following message:

`Mixed Content: The page at 'https://dev.returnlambda.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://parks.api.codefornrv.org/amenity_type'. This request has been blocked; the content must be served over HTTPS.`

**Comment by nealf** [comment]
All content is now redirected to and served over ssl! :-)
